### ISSUE TITLE
Beginner -> Core -> first two courses

### ISSUE THREAD

**Issue by jasonwedepohl** [Enteleform/-RES-#1]
On links.md under Beginner Core courses, the "UI Design" link is redirecting to the same page as the "App Development 1" link (even though their urls are different).

PS. This repo is a great reference. Thanks for putting it together.

**Comment by Enteleform** [comment]
Thanks for the heads up. That was actually a recent addition, I just added it about a month ago when I saw that there were a few new courses on Udacity. Looks like they might have merged some of the courses since then.
